version: "3.9"

services:
  printer-be:
    container_name: printer-be
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "6000:8443"
      - "5005:5005"
    environment:
      JAVA_TOOL_OPTIONS: >
        -Xmx128m -Xms64m -XX:+UseSerialGC
        -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
    restart: unless-stopped
    networks:
      - printer-net
  kafka:
    image: apache/kafka:latest
    container_name: printer-be-kafka
    hostname: broker
    ports:
      - "4076:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://217.160.248.228:4076
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_NUM_PARTITIONS: 3
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
    tmpfs:
      - /tmp/kraft-combined-logs
    restart: unless-stopped
    networks:
      - printer-net
    healthcheck:
      test: [ "CMD-SHELL", "kafka-broker-api-versions.sh --bootstrap-server localhost:9092 | grep -q 'sasl_plaintext'|| kafka-broker-api-versions.sh --bootstrap-server localhost:9092" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

networks:
  printer-net:
    driver: bridge