version: "3.9"

services:
  printer-be:
    container_name: printer-be
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "6000:8443"
      - "5005:5005"
    environment:
      JAVA_TOOL_OPTIONS: >
        -Xmx128m -Xms64m -XX:+UseSerialGC
        -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
    restart: unless-stopped
    networks:
      - printer-net

networks:
  printer-net:
    driver: bridge
