spring:
  application:
    name: 3D Printer BE

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

  kafka:
    bootstrap-servers: ${PRINTER_KAFKA_URL}
    consumer:
      group-id: printer-server

  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${PRINTER_DB_URL}
    username: ${PRINTER_DB_USERNAME}
    password: ${PRINTER_DB_PASSWORD}
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      connection-timeout: 20000
      idle-timeout: 300000

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          batch_size: 20
          order_inserts: true
          order_updates: true
        cache:
          use_second_level_cache: false

  devtools:
    restart:
      enabled: false

  sql:
    init:
      mode: always

  task:
    execution:
      pool:
        core-size: 2
        max-size: 5
        queue-capacity: 10
        thread-name-prefix: "printer-async-"
        keep-alive: "60s"

server:
  address: 0.0.0.0
  port: 8443
  ssl:
    enabled: true
    key-store: classpath:keystore.p12
    key-store-password: ${PRINTER_KEYSTORE_PASSWORD}
    key-store-type: PKCS12
  compression:
    enabled: true
  http2:
    enabled: true

logging:
  level:
    root: WARN
    org.springframework.security: DEBUG
    org.hibernate.SQL: ERROR
    org.hibernate.type.descriptor.sql: ERROR
    it.aredegalli: DEBUG
    org.springframework.web: DEBUG
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"

security:
  cors:
    allowed-origins: "*"
    allowed-methods: "*"
    allowed-headers: "*"
    allow-credentials: false
    max-age: 3600
  whitelist:
    ips: ${PRINTER_WHITELIST_IPS:127.0.0.1,::1}
  crypto:
    aes-secret-key: ${PRINTER_AES_KEY}

management:
  endpoints:
    web:
      exposure:
        include: health, info, beans, metrics, env
      base-path: /actuator
  endpoint:
    health:
      show-details: always
      show-components: always
  info:
    git:
      mode: full
    env:
      enabled: true
  health:
    db:
      enabled: true
    diskspace:
      enabled: true

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    operationsSorter: method
    tagsSorter: alpha
  show-actuator: true

hmac:
  secret:
    key: ${HMAC_SECRET_KEY}

minio:
  endpoint: ${MINIO_ENDPOINT}
  access-key: ${MINIO_ACCESS_KEY}
  secret-key: ${MINIO_SECRET_KEY}
  port: ${MINIO_PORT:9000}
  region: ${MINIO_REGION:us-east-1}
  bucket-name: ${MINIO_BUCKET_NAME:3d-printer-files}

external-services:
  stl2glb:
    url: ${STL2GLB_SERVICE_URL:http://dev.aredegalli.it:9002}
    timeout: 30s
    retry-attempts: 3

stl2glb:
  url: ${STL2GLB_SERVICE_URL:http://dev.aredegalli.it:9002}

jwt:
  secret: ${PRINTER_JWT_SECRET}
  expiration: 300

slicing:
  default-engine: ${SLICING_DEFAULT_ENGINE:CuraEngine}

  queue:
    processing:
      enabled: ${SLICING_PROCESSING_ENABLED:true}
      max-concurrent: ${SLICING_MAX_CONCURRENT:2}
      batch-size: ${SLICING_BATCH_SIZE:5}
    stale-timeout-minutes: ${SLICING_STALE_TIMEOUT:30}

  engines:
    external:
      enabled: ${SLICING_EXTERNAL_ENABLED:true}
      service-url: ${EXTERNAL_SLICER_URL:http://dev.aredegalli.it:4075}
      timeout-seconds: 300
      connection-timeout-seconds: 30

  default:
    build-volume:
      width: 200
      depth: 200
      height: 200

deployment:
  url: ${PRINTER_DEPLOYMENT_URL:http://localhost:8443}